/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
 * Generated on: 21-Mar-2019 10:38:45
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : single
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int b_len[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const float b[MWSPT_NSEC][3] = {
  {
    0.01381897461,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
    0.01242102683,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
     0.1093568951,              0,              0 
  },
  {
                1,              1,              0 
  },
  {
                1,              0,              0 
  }
};
const int a_len[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const float a[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.805608511,    0.860884428 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.622950554,   0.6726346612 
  },
  {
                1,              0,              0 
  },
  {
                1,    -0.78128618,              0 
  },
  {
                1,              0,              0 
  }
};
